<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Extensions\**\*.cs"/>
    <None Include="Extensions\**\*.cs"/>
  </ItemGroup>
  <PropertyGroup Label="Globals">
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.1"/>
    <!--<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.MSBuild" Version="6.2.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Extensions\ZentraBuilder.cs"/>
    <Compile Include="Extensions\ZentraExtension.cs"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zentra.Identity.DomainServices\Zentra.DomainServices.csproj"/>
    <ProjectReference Include="..\Zentra.Identity.Persistence\Zentra.Infrastructure.Data.csproj"/>
    <ProjectReference Include="..\Zentra.Identity.Infrastructure.Resources\Zentra.Infrastructure.Resources.csproj"/>
    <ProjectReference Include="..\Zentra.Identity.Infrastructure\Zentra.Infrastructure.Services.csproj"/>
    <ProjectReference Include="..\..\Gateway\Zentra.Gateway\Zentra.ProxyService.csproj"/>
    <ProjectReference Include="..\Zentra.Identity.Application\Zentra.Service.csproj"/>
  </ItemGroup>

</Project>
