// <auto-generated />
using System;
using HCL.CS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCL.CS.Infrastructure.Data.Migrations.Sqlite;

[DbContext(typeof(SqLiteApplicationDbContext))]
[Migration("20260728135000_FixSqliteBaselineDeduplication")]
partial class FixSqliteBaselineDeduplication
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
    }
}
