<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\installer\HCL.CS.Installer.Mvc\HclCsInstallerMVC.csproj"/>
    <ProjectReference Include="..\..\src\Identity\HCL.CS.Identity.Persistence\HCL.CS.Infrastructure.Data.csproj"/>
  </ItemGroup>
</Project>
