<!--
Copyright (c) 2021 HCL CORPORATION.
All rights reserved. HCL source code is an unpublished work and the use of a copyright notice does not imply otherwise.
This source code contains confidential, trade secret material of HCL. Any attempt or participation in deciphering,
decoding, reverse engineering or in any way altering the source code is strictly prohibited, unless the prior written consent of
HCL is obtained. This is proprietary and confidential to HCL.
-->

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateMvcApplicationPartsAssemblyAttributes>false</GenerateMvcApplicationPartsAssemblyAttributes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure/Persistence/Migrations/Sqlite/20220802110433_HclCsSqliteV1.cs"/>
    <Compile Remove="Infrastructure/Persistence/Migrations/Sqlite/20220802110433_HclCsSqliteV1.Designer.cs"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Identity\HCL.CS.Identity.Domain\HCL.CS.Domain.csproj"/>
    <ProjectReference Include="..\..\src\Identity\HCL.CS.Identity.Persistence\HCL.CS.Infrastructure.Data.csproj"/>
    <ProjectReference Include="..\..\src\Identity\HCL.CS.Identity.Application\HCL.CS.Service.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11"/>
    <PackageReference Include="MySql.Data" Version="8.0.29"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2"/>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3"/>
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4"/>
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1"/>
    <PackageReference Include="System.Text.Json" Version="8.0.6"/>
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="App_Data\installer.lock.json"/>
  </ItemGroup>

</Project>
