apiVersion: v1
kind: Service
metadata:
  name: zentra-admin
  labels:
    app: zentra-admin
spec:
  selector:
    app: zentra-admin
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
