apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcl-cs-identity
  labels:
    app: hcl-cs-identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hcl-cs-identity
  template:
    metadata:
      labels:
        app: hcl-cs-identity
    spec:
      containers:
        - name: identity-api
          image: hcl-cs/identity-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hcl-cs-config
