apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcl-cs-ingress
spec:
  rules:
    - host: hcl-cs.local
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: hcl-cs-identity
                port:
                  number: 80
