<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Identity\Zentra.Identity.DomainServices\Zentra.DomainServices.csproj"/>
    <ProjectReference Include="..\..\Identity\Zentra.Identity.Domain\Zentra.Domain.csproj"/>
    <ProjectReference Include="..\..\Identity\Zentra.Identity.Contracts\Zentra.Service.Interfaces.csproj"/>
    <ProjectReference Include="..\..\Identity\Zentra.Identity.Application\Zentra.Service.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <!--<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="StyleCop.MSBuild" Version="6.2.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>-->
  </ItemGroup>

</Project>

