//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL.CS.Infrastructure.Resources
{
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCL.CS.Infrastructure.Resources", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AUD1001 {
            get {
                return ResourceManager.GetString("AUD1001", resourceCulture);
            }
        }
        
        public static string AUD1002 {
            get {
                return ResourceManager.GetString("AUD1002", resourceCulture);
            }
        }
        
        public static string AUD1003 {
            get {
                return ResourceManager.GetString("AUD1003", resourceCulture);
            }
        }
        
        public static string AUT2001 {
            get {
                return ResourceManager.GetString("AUT2001", resourceCulture);
            }
        }
        
        public static string AUT2002 {
            get {
                return ResourceManager.GetString("AUT2002", resourceCulture);
            }
        }
        
        public static string AUT2003 {
            get {
                return ResourceManager.GetString("AUT2003", resourceCulture);
            }
        }
        
        public static string AUT2004 {
            get {
                return ResourceManager.GetString("AUT2004", resourceCulture);
            }
        }
        
        public static string AUT2005 {
            get {
                return ResourceManager.GetString("AUT2005", resourceCulture);
            }
        }
        
        public static string AUT2006 {
            get {
                return ResourceManager.GetString("AUT2006", resourceCulture);
            }
        }
        
        public static string AUT2007 {
            get {
                return ResourceManager.GetString("AUT2007", resourceCulture);
            }
        }
        
        public static string AUT2008 {
            get {
                return ResourceManager.GetString("AUT2008", resourceCulture);
            }
        }
        
        public static string AUT2009 {
            get {
                return ResourceManager.GetString("AUT2009", resourceCulture);
            }
        }
        
        public static string AUT2010 {
            get {
                return ResourceManager.GetString("AUT2010", resourceCulture);
            }
        }
        
        public static string AUT2011 {
            get {
                return ResourceManager.GetString("AUT2011", resourceCulture);
            }
        }
        
        public static string AUT2012 {
            get {
                return ResourceManager.GetString("AUT2012", resourceCulture);
            }
        }
        
        public static string COM5001 {
            get {
                return ResourceManager.GetString("COM5001", resourceCulture);
            }
        }
        
        public static string COM5002 {
            get {
                return ResourceManager.GetString("COM5002", resourceCulture);
            }
        }
        
        public static string COM5003 {
            get {
                return ResourceManager.GetString("COM5003", resourceCulture);
            }
        }
        
        public static string COM5004 {
            get {
                return ResourceManager.GetString("COM5004", resourceCulture);
            }
        }
        
        public static string COM5005 {
            get {
                return ResourceManager.GetString("COM5005", resourceCulture);
            }
        }
        
        public static string COM5006 {
            get {
                return ResourceManager.GetString("COM5006", resourceCulture);
            }
        }
        
        public static string CRY3001 {
            get {
                return ResourceManager.GetString("CRY3001", resourceCulture);
            }
        }
        
        public static string CRY3002 {
            get {
                return ResourceManager.GetString("CRY3002", resourceCulture);
            }
        }
        
        public static string CRY3003 {
            get {
                return ResourceManager.GetString("CRY3003", resourceCulture);
            }
        }
        
        public static string CRY3004 {
            get {
                return ResourceManager.GetString("CRY3004", resourceCulture);
            }
        }
        
        public static string CRY3005 {
            get {
                return ResourceManager.GetString("CRY3005", resourceCulture);
            }
        }
        
        public static string CRY3006 {
            get {
                return ResourceManager.GetString("CRY3006", resourceCulture);
            }
        }
        
        public static string CRY3007 {
            get {
                return ResourceManager.GetString("CRY3007", resourceCulture);
            }
        }
        
        public static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }
        
        public static string E1002 {
            get {
                return ResourceManager.GetString("E1002", resourceCulture);
            }
        }
        
        public static string E1003 {
            get {
                return ResourceManager.GetString("E1003", resourceCulture);
            }
        }
        
        public static string E1006 {
            get {
                return ResourceManager.GetString("E1006", resourceCulture);
            }
        }
        
        public static string E1008 {
            get {
                return ResourceManager.GetString("E1008", resourceCulture);
            }
        }
        
        public static string E1010 {
            get {
                return ResourceManager.GetString("E1010", resourceCulture);
            }
        }
        
        public static string USR4001 {
            get {
                return ResourceManager.GetString("USR4001", resourceCulture);
            }
        }
        
        public static string USR4002 {
            get {
                return ResourceManager.GetString("USR4002", resourceCulture);
            }
        }
        
        public static string USR4003 {
            get {
                return ResourceManager.GetString("USR4003", resourceCulture);
            }
        }
        
        public static string USR4004 {
            get {
                return ResourceManager.GetString("USR4004", resourceCulture);
            }
        }
        
        public static string USR4005 {
            get {
                return ResourceManager.GetString("USR4005", resourceCulture);
            }
        }
        
        public static string USR4006 {
            get {
                return ResourceManager.GetString("USR4006", resourceCulture);
            }
        }
        
        public static string USR4007 {
            get {
                return ResourceManager.GetString("USR4007", resourceCulture);
            }
        }
        
        public static string USR4008 {
            get {
                return ResourceManager.GetString("USR4008", resourceCulture);
            }
        }
        
        public static string USR4009 {
            get {
                return ResourceManager.GetString("USR4009", resourceCulture);
            }
        }
        
        public static string USR4010 {
            get {
                return ResourceManager.GetString("USR4010", resourceCulture);
            }
        }
        
        public static string USR4011 {
            get {
                return ResourceManager.GetString("USR4011", resourceCulture);
            }
        }
        
        public static string USR4012 {
            get {
                return ResourceManager.GetString("USR4012", resourceCulture);
            }
        }
        
        public static string USR4013 {
            get {
                return ResourceManager.GetString("USR4013", resourceCulture);
            }
        }
    }
}



